MODE_NON_STREAM = "1"
MODE_NON_STREAM_POLISH = "2"
MODE_REALTIME = "3"
MODE_REALTIME_POLISH = "4"

MODE_CHOICES = (
    MODE_NON_STREAM,
    MODE_NON_STREAM_POLISH,
    MODE_REALTIME,
    MODE_REALTIME_POLISH,
)
